### ISSUE TITLE
body/repository must be an object

### ISSUE THREAD

**Issue by leorossi** [platformatic/onestep#6]
While trying to deploy https://github.com/leorossi/demo-app/actions I get this error

```
{"type":"Error","message":"body/repository must be object","stack":"Error: body/repository must be object\n at defaultSchemaErrorFormatter (/opt/steve/node_modules/fastify/lib/context.js:107:10)\n at wrapValidationError (/opt/steve/node_modules/fastify/lib/validation.js:131:17)\n at validate (/opt/steve/node_modules/fastify/lib/validation.js:111:12)\n at preValidationCallback (/opt/steve/node_modules/fastify/lib/handleRequest.js:92:18)\n at handler (/opt/steve/node_modules/fastify/lib/handleRequest.js:76:7)\n at /opt/steve/node_modules/fastify/lib/contentTypeParser.js:190:9\n at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n at done (/opt/steve/node_modules/fastify/lib/contentTypeParser.js:184:14)\n at Parser.defaultJsonParser [as fn] (/opt/steve/node_modules/fastify/lib/contentTypeParser.js:290:5)\n at IncomingMessage.onEnd (/opt/steve/node_modules/fastify/lib/contentTypeParser.js:269:27)","statusCode":400,"validation":[{"instancePath":"/repository","schemaPath":"#/properties/repository/type","keyword":"type","params":{"type":"object"},"message":"must be object"}],"validationContext":"body"},"msg":"body/repository must be object"}
```

This is the action: https://github.com/leorossi/demo-app/actions/runs/3628413069/jobs/6119397313

**Comment by ivan-tymoshenko** [comment]
@leorossi update action to v0.0.7

**Comment by ivan-tymoshenko** [comment]
Check readme
https://github.com/platformatic/onestep/blob/main/README.md

**Comment by leorossi** [comment]
Fixed! Thanks
