### ISSUE TITLE
broken onestep action: using: node18 is not supported

### ISSUE THREAD

**Issue by Eomm** [platformatic/onestep#78]
I got this error today:

```
Download action repository 'platformatic/onestep@latest' (SHA:c9080dfdce7351a69081b26d7b1d536badc3257a)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load platformatic/onestep/latest/action.yml
```

GH Action Run https://github.com/Eomm/telegram-bot-give-away/actions/runs/6130477184/job/16639602008?pr=5

I can confirm the issue at this commit too: https://github.com/platformatic/onestep/commit/f4b19b11c589d462b1712be730aae107c7688fbe

I pinned my GHA to this commit to solve: https://github.com/platformatic/onestep/commit/85911c6d508df1e96437f814e0a854010d55f11d

**Comment by mcollina** [comment]
Fixes and moved to node20 instead.

Good spot!
